ALTER TABLE monsters MODIFY COLUMN template TEXT NOT NULL;
ALTER TABLE raid MODIFY COLUMN template TEXT NOT NULL;
ALTER TABLE egg MODIFY COLUMN template TEXT NOT NULL;
ALTER TABLE quest MODIFY COLUMN template TEXT NOT NULL;
ALTER TABLE invasion MODIFY COLUMN template TEXT NOT NULL;
