CREATE TABLE IF NOT EXISTS gym (
  uid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(255) NOT NULL,
  profile_no INT NOT NULL DEFAULT 1,
  ping VARCHAR(255) NOT NULL,
  clean TINYINT(1) NOT NULL DEFAULT 0,
  distance INT NOT NULL,
  template TEXT NOT NULL,
  team INT NOT NULL,
  slot_changes TINYINT(1) NOT NULL,
  gym_id VARCHAR(255) NULL,
  CONSTRAINT gym_id_foreign FOREIGN KEY (id) REFERENCES humans(id) ON DELETE CASCADE
) ENGINE=InnoDB;
