CREATE TABLE IF NOT EXISTS forts (
  uid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(255) NOT NULL,
  profile_no INT NOT NULL DEFAULT 1,
  ping VARCHAR(255) NOT NULL,
  distance INT NOT NULL,
  template TEXT NOT NULL,
  fort_type VARCHAR(255) NOT NULL DEFAULT 'everything',
  include_empty TINYINT(1) NOT NULL DEFAULT 1,
  change_types VARCHAR(255) NOT NULL DEFAULT '[]',
  CONSTRAINT forts_id_foreign FOREIGN KEY (id) REFERENCES humans(id) ON DELETE CASCADE
) ENGINE=InnoDB;
