CREATE TABLE IF NOT EXISTS maxbattle (
  uid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(255) NOT NULL,
  profile_no INT NOT NULL DEFAULT 1,
  ping VARCHAR(255) NOT NULL,
  clean TINYINT(1) NOT NULL DEFAULT 0,
  pokemon_id INT NOT NULL,
  gmax TINYINT(1) NOT NULL DEFAULT 0,
  template TEXT NOT NULL,
  distance INT NOT NULL,
  level INT NOT NULL DEFAULT 0,
  form INT NOT NULL DEFAULT 0,
  move INT NOT NULL DEFAULT 9000,
  evolution INT NOT NULL DEFAULT 9000,
  station_id VARCHAR(255) DEFAULT NULL,
  CONSTRAINT maxbattle_id_foreign FOREIGN KEY (id) REFERENCES humans(id) ON DELETE CASCADE
) ENGINE=InnoDB;

